### ISSUE TITLE
nvidia-drivers  security update Okrober 2024

### ISSUE THREAD

**Issue by org-tekeli-borisp** [macaroni-os/mark-issues#188]
Reported by @cuantar See https://nvidia.custhelp.com/app/answers/detail/a_id/5586

**Comment by geaaru** [comment]
I will try to integrate my overlay's generator with MARK (now doesn't consider some postinst/postremove actions because managed directly by anise).
https://github.com/geaaru/geaaru_overlay/commit/74e988e14604fa55ea3db5a3f4c72e7bab95c2b4

The version defined in the links are not yet available [here](https://download.nvidia.com/XFree86/Linux-x86_64/)
