### ISSUE TITLE
[bug] [metatools] `merge-kits` writes to `stderr` even when there is nothing apparently wrong

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#57]
The following shows up from my `cron` jobs after every tree regen, along with ~1000 kb of `stdout` text:

```
ERROR OUTPUT:
    Updating crates.io index
```

If this isn't an error, it should be quiet.  If it is an error, then it is a bug that we should fix.

**Comment by cuantar** [comment]
![image](https://github.com/user-attachments/assets/f0c43bd2-dd8d-4c26-9ede-c6615c430993)

**Comment by cuantar** [comment]
Some exploration reveals:
- the output messages seem to be associated with the line immediately following
- none of these packages produces the offending message when generated manually with `doit --pkg ...`

**Comment by cuantar** [comment]
![image](https://github.com/user-attachments/assets/08e8f2a4-82e1-40ee-9e8d-e6373972b445)

Here's a subsequent run of `merge-kits`.  It seems the output message is coming from something called within multiple ebuilds, so it doesn't occur at the same place.

**Comment by geaaru** [comment]
@cuantar the output of the `Updating creates.io` is related to the autogen module that executes the generation of the bundle for Rust stuff. It's verbose but i fear that quiet it means hiding the errors if they happen.
Maybe, would be good to have the output only when there are issues but will be in any case a bit complex because elaborate things in parallel are always complex to debug.
So, if you want to reduce that output you need to investigate in the module that manages rust/cargo packages.

**Comment by geaaru** [comment]
Considering the retirement of funtoo-metatools from his creator I prefer follow his wish and implement a new autogen tool better integrate to CDN. I close this issue. Feel free to open a RFC's issue with the description of the feature for mark-devkit tool.
