### ISSUE TITLE
[bug] [emerge] [autogen] Pin NetworkManager to latest version that builds in our tree, `1.48.6`

### ISSUE THREAD

**Issue by cuantar** [macaroni-os/mark-issues#68]
We can fix NM by pinning the version to something; so let's pick the latest version that compiles successfully.  Known good was `1.48.6`.

**Comment by geaaru** [comment]
Just to trace a note about this.

The issue with the symbol IFLA_BOND_SLAVE_PRIO could be related to our `linux-headers` package:

https://github.com/torvalds/linux/blob/master/tools/include/uapi/linux/if_link.h#L1005

We need to try to upgrade linux-headers to kernel 6.x and check if the problem is yet present.

Upgrading `linux-headers` could impact multiple packages so it's correct to ping version 1.48.6 and unpin the version when `mark-testing` release is available. My cent.

**Comment by cepelinas9000** [comment]
IFLA_BOND_SLAVE_PRIO was introduced in kernel 6.0 on Jun 24, 2022 ( https://github.com/torvalds/linux/commit/0a2ff7cc8ad48a86939a91bd3457f38e59e741a1 ). 

There will be multiple packages which where impacted due to removed definitions. for example busybox (https://bugs.gentoo.org/926872 )

**Comment by geaaru** [comment]
@cepelinas9000 thanks for the comment. It's helpful. 

So, this confirms that it's better to pin the version and upgrade the `linux-headers` package in a safe environment for testing.

**Comment by cuantar** [comment]
I concur.  Let's pin the version here and test `linux-headers` in a safe testing tree.  I'll check whether `1.48.7` builds.

**Comment by org-tekeli-borisp** [comment]
With llinux-headers-6.9 networkmanager-1.48.8 emerges successfully 
![image](https://github.com/user-attachments/assets/7b9c5294-3231-40eb-9bb6-d829f8fe43ab)

**Comment by cuantar** [comment]
There is no `networkmanager-1.48.7` release tarball, so maybe it exists as a dev version and they follow an even/odd cycle.  Haven't verified.  Regardless, `1.48.6` is the highest available version that works for us until we update our kernel headers.

**Comment by geaaru** [comment]
Just a little conclusion:
* on `master` (next branch) we pin 1.48.6
* on `mark-testing` with the upgrade of linux-headers we don't need to pin the version.
